server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: genres-with-movies
          uri: http://localhost:8081
          predicates:
            - Path=/genres/with-movies
        - id: movie-service
          uri: http://localhost:8081
          predicates:
            - Path=/genres/*/movies/**
        - id: genre-service
          uri: http://localhost:8080
          predicates:
            - Path=/genres/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
